// Artist replacements

const REPLACEMENTS = {
    ARTIST: {
        'Goddess Athalia': 'Goddess Athalia Trance Treats',
        'Selene Rey': ['Selene Rey', 'SeleneRey', 'selenerey', 'SeleneRey Demands', 'Selene Rey Demands'],
        'Goddess Alexa': ['iAmGoddessAlexa', 'iamgoddessalexa', 'i Am Goddess Alexa'],
        'Roxanne Miller': ['RoxanneMiller', 'Roxanne Miller', 'TheRoxanneMiller', 'The Roxanne Miller'],
        'Raven Kiss': ['raven_kiss'],
        'Madison Stone': ['MissMadisonStone', 'missmadisonstone', 'Miss Madison Stone', 'Miss Madison'],
        'Princess Brielle': ['Princess Brielle FinDom FemDom'],
        'Goddess J': ['Jewish Goddess J Findom Hypn0sis', 'littlefootsiejen', 'LittleFootsieJen', 'Little Footsie Jen'],
        'Aria Zahara': ['Goddess Aria Zahara'],
        'Ivy Doll': ['MissIvyDoll', 'Miss Ivy Doll'],
        'Maggie Rose (maggierosexo)': ['maggierosexo'],
        'Nina Leigh': ['Lady Nina'],
        'Gia Blaze': ['Onlygiablaze', 'onlygiablaze'],
        'Persephone Pink (Sephy Pink)': ['SephyPink', 'Sephy Pink'],
        'Sloane Sabbath': ['sloane sabbath'],
        'Sophia Truee': ['Miss Sophia Truee'],
        'Tara Babcock': ['tarababcock'],
        'THEcherrygirl': ['THEcherryGirl', 'THEcherry Girl', 'Thecherrygirl'],
        'Goddess Velvet': ['Thevelvetgoddess', 'TheVelvetGoddess', 'The Velvet Goddess', 'TheTrueVelvetGoddess', 'The True Velvet Goddess'],
        'Goddess Vanessa (dommebombshell)': ['Goddess Vanessa'],
        'Versona': ['Goddess Versona'],
        'Worship Jasmine': ['Worship Goddess Jasmine'],
        'Yolly Sabra': ['Yolly_Sabra', 'Goddess Yolanda Sabra Femdom Findom Sensual Domination', 'yollysabra'],
        'Miss Lace': ['Miss Lovely Lace', 'MissLovelyLace'],
        'Goddess Tina': ['GoddessTina1', 'Goddess Tina 1'],
        'Enigma': ['EnigmaMGF', 'Enigma MGF'],
        'Goddess Victoria': ['Cruel Seductress Victoria'],
        'Jessica Starling': ['Jessica Starling XXX', 'Mistress Jessica Starling'],
        'Worship Amanda': ['Goddess Amanda', 'The Goddess Amanda'],
        'Savannah Siren': ['SavannahxSiren', 'Savannahx Siren'],
        'Stella Purr': ['Miss Stella Purr'],
        'Roxanne Miller': ['The Roxanne Miller', 'RoxanneMiller', 'Roxanne Miller'],
        'Ava Onyx': ['iworshipavaonyx'],
        'Sienna Foxx': ['Vindictive Vixxen Humiliates You', 'Vindictive Vixxen', 'Mz Sienna Foxx - Fetish Goddess', 'Mz Sienna Foxx', 'MzSiennaFoxx', 'mzsiennafoxx'],
        'Princess Michelle': ['Princess Michelle Clips', 'Saint Michelle', 'saintmichelle'],
        'Mistress Ezada Sinn': ['Ezada Sinn', 'Ezada'],
        'Kendall Olsen': ['Goddess Kendall'],
        'Lexi Chill (LATEXnCHILL)': ['LATEXnCHILL', 'LATEXn CHILL', 'Latexnchill', 'latexnchill', 'Lexi Chill'],
        'Natasha\'s Bedroom': ['Natashas Bedroom'],
        'Noel Knight': ['Mistress Noel Knight'],
        'Miss Tiff': ['Tiffany James'],
        'Lovely Lilith': ['Lovely Lilith\'s Lusty Lair'],
        'Alexsis Faye': ['alexsisfaye'],
        'Goddess Danielle (Queen Deserves)': ['Goddess Danielle', 'Queen Deserves', 'Queendeserves', 'queendeserves'],
        'Kelle Martina': ['Miss Kelle Martina'],
        'Ama Bentley': ['Spanish Ama Bentley', 'Mental Domme Bentley', 'MENTAL DOMME BENTLEY', 'mentaldommebentley', 'Jessyka Bentley'],
        'Danielle Maye': ['Danielle Maye XXX'],
        'Madam Violet': ['Goddess Madam Violet'],
        'Goddess Valora': ['Goddess Valoras Femdom POV', 'Goddess_Valora', 'goddess_valora'],
        'CutieDaisyMay093': ['Cutie Daisy May093'],
        'Cute Jayne': ['Cutejayne'],
    },
    TITLE: {
        '\'': ['`', '’'],
        '-': ['–'],
        ' - ': [' : ', ': ', ' :', ':', ' - ', '- ', ' -'],
        'Step-Mo': ['stepMo', 'StepMo', 'step-Mo'],
        'STEP-MO': ['stepMO', 'StepMO', 'step-MO', 'Step-MO'],
        'Step-So': ['stepSo', 'StepSo', 'step-So'],
        'STEP-SO': ['stepSO', 'StepSO', 'step-SO', 'Step-SO'],
        'Step-Si': ['stepSi', 'StepSi', 'step-Si'],
        'STEP-SI': ['stepSI', 'StepSI', 'step-SI', 'Step-SI'],
        'Step-Da': ['stepDa', 'StepDa', 'step-Da'],
        'STEP-DA': ['stepDA', 'StepDA', 'step-DA', 'Step-DA'],
        'Step-Br': ['stepBr', 'StepBr', 'step-Br'],
        'STEP-BR': ['stepBR', 'StepBR', 'step-BR', 'Step-BR'],
        '': [' 1080p', ' 720p',' 4K', ' 4k'],
        ' JOI ': [' Joi ', ' joi '],
    },
};
