// Artist replacements

const REPLACEMENTS = {
    ARTIST: {
        'Goddess Athalia': 'Goddess Athalia Trance Treats',
        'Selene Rey': ['SeleneRey', 'selenerey', 'SeleneRey Demands'],
        'Goddess Alexa': ['iAmGoddessAlexa', 'iamgoddessalexa'],
        'Roxanne Miller': 'RoxanneMiller',
        'Raven Kiss': ['raven_kiss'],
        'Madison Stone': ['MissMadisonStone', 'missmadisonstone', 'Miss Madison Stone', 'Miss Madison'],
        'Princess Brielle': ['Princess Brielle FinDom FemDom'],
        'Goddess J': ['Jewish Goddess J Findom Hypn0sis', 'littlefootsiejen', 'LittleFootsieJen'],
        'Aria Zahara': ['Goddess Aria Zahara'],
        'Ivy Doll': ['MissIvyDoll', 'Miss Ivy Doll'],
        'Maggie Rose (maggierosexo)': ['maggierosexo'],
        'Nina Leigh': ['Lady Nina'],
        'Gia Blaze': ['Onlygiablaze', 'onlygiablaze'],
        'Persephone Pink (Sephy Pink)': ['SephyPink', 'Sephy Pink'],
        'Sloane Sabbath': ['sloane sabbath'],
        'Sophia Truee': ['Miss Sophia Truee'],
        'Tara Babcock': ['tarababcock'],
        'THEcherrygirl': ['THEcherryGirl', 'Thecherrygirl'],
        'Goddess Velvet': ['Thevelvetgoddess', 'TheVelvetGoddess', 'TheTrueVelvetGoddess'],
        'Goddess Vanessa (dommebombshell)': ['Goddess Vanessa'],
        'Versona': ['Goddess Versona'],
        'Worship Jasmine': ['Worship Goddess Jasmine'],
        'Yolly Sabra': ['Yolly_Sabra', 'Goddess Yolanda Sabra Femdom Findom Sensual Domination', 'yollysabra'],
        'Miss Lace': ['Miss Lovely Lace', 'MissLovelyLace'],
        'Goddess Tina': ['GoddessTina1'],
        'Enigma': ['EnigmaMGF'],
        'Goddess Victoria': ['Cruel Seductress Victoria'],
        'Jessica Starling': ['Jessica Starling XXX', 'Mistress Jessica Starling'],
        'Worship Amanda': ['Goddess Amanda'],
        'Savannah Siren': ['SavannahxSiren'],
        'Stella Purr': ['Miss Stella Purr'],
        'Roxanne Miller': ['The Roxanne Miller', 'RoxanneMiller'],
    },
    TITLE: {
        '\'': ['`', '’'],
        '-': ['–'],
        ' - ': [' ?: ?'],
        'Step-Mo': ['stepMo', 'StepMo', 'step-Mo'],
        'Step-So': ['stepSo', 'StepSo', 'step-So'],
        'Step-Si': ['stepSi', 'StepSi', 'step-Si'],
        'Step-Da': ['stepDa', 'StepDa', 'step-Da'],
        'Step-Br': ['stepBr', 'StepBr', 'step-Br'],
        '': [' 1080p', ' 720p',' 4K'],
    },
};
